; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.12"

; MODULES - Mandatory

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"


; MODULES - Generic modules
; MODULES - Fields
; MODULES - Feeds
; MODULES - Developer

projects[devel][subdir] = "sites/all/modules/contrib/devel"

; MODULES - Views

projects[better_exposed_filters][subdir] = "sites/all/modules/contrib/better_exposed_filters"
projects[views_bulk_operations][subdir] = "sites/all/modules/contrib/views_bulk_operations"

; MODULES - Context

projects[context][subdir] = "sites/all/modules/contrib/context"


; MODULES - Panels

projects[panels][subdir] = "sites/all/modules/contrib/panels"
projects[panels_breadcrumbs][subdir] = "sites/all/modules/contrib/panels_breadcrumbs"

; MODULES - i18n
; MODULES - Rules
; MODULES - Search engines
; MODULES - Breadcrumbs
; MODULES - Performance
; MODULES - System
; MODULES - Mail

; MODULES - Taxonomy
; MODULES - Menu

; MODULES - Geolocation

projects[addressfield][subdir] = "sites/all/modules/contrib/addressfield"

; MODULES - Editing contents

;permette di impostare un limite di tempo o di revisioni oltre il quale non è possibile più modificare per l'autore il contenuto
projects[edit_limit][subdir] = "sites/all/modules/contrib/edit_limit"

projects[auto_nodetitle][subdir] = "sites/all/modules/contrib/auto_nodetitle"

projects[boxes][subdir] = "sites/all/modules/contrib/boxes"

projects[node_clone][subdir] = "sites/all/modules/contrib/node_clone"

projects[css_injector][subdir] = "sites/all/modules/contrib/css_injector"

projects[facetapi][subdir] = "sites/all/modules/contrib/facetapi"

projects[custom_breadcrumbs][subdir] = "sites/all/modules/contrib/custom_breadcrumbs"

projects[date][subdir] = "sites/all/modules/contrib/date"

projects[diff][subdir] = "sites/all/modules/contrib/diff"

projects[elysia_cron][subdir] = "sites/all/modules/contrib/elysia_cron"

projects[email][subdir] = "sites/all/modules/contrib/email"

projects[entity][subdir] = "sites/all/modules/contrib/entity"

projects[facetapi_bonus][subdir] = "sites/all/modules/contrib/facetapi_bonus"

projects[features][subdir] = "sites/all/modules/contrib/features"

projects[features_orphans][subdir] = "sites/all/modules/contrib/features_orphans"

projects[feeds][subdir] = "sites/all/modules/contrib/feeds"

projects[feeds_fetcher_directory][subdir] = "sites/all/modules/contrib/feeds_fetcher_directory"

projects[feeds_tamper][subdir] = "sites/all/modules/contrib/feeds_tamper"

projects[feeds_xpathparser][subdir] = "sites/all/modules/contrib/feeds_xpathparser"

projects[field_group][subdir] = "sites/all/modules/contrib/field_group"

projects[media][subdir] = "sites/all/modules/contrib/media"

projects[styles][subdir] = "sites/all/modules/contrib/styles"

projects[geofield][subdir] = "sites/all/modules/contrib/geofield"

projects[google_analytics][subdir] = "sites/all/modules/contrib/google_analytics"

projects[hint][subdir] = "sites/all/modules/contrib/hint"

projects[i18n][subdir] = "sites/all/modules/contrib/i18n"

projects[imagecrop][subdir] = "sites/all/modules/contrib/imagecrop"

projects[jcarousel][subdir] = "sites/all/modules/contrib/jcarousel"

projects[job_scheduler][subdir] = "sites/all/modules/contrib/job_scheduler"

projects[languageicons][subdir] = "sites/all/modules/contrib/languageicons"

projects[libraries][subdir] = "sites/all/modules/contrib/libraries"

projects[link][subdir] = "sites/all/modules/contrib/link"

projects[linkit][subdir] = "sites/all/modules/contrib/linkit"

projects[mailchimp][subdir] = "sites/all/modules/contrib/mailchimp"

projects[media_colorbox][subdir] = "sites/all/modules/contrib/media_colorbox"

projects[media_youtube][subdir] = "sites/all/modules/contrib/media_youtube"

projects[memcache][subdir] = "sites/all/modules/contrib/memcache"

projects[menu_attributes][subdir] = "sites/all/modules/contrib/menu_attributes"

projects[menu_block][subdir] = "sites/all/modules/contrib/menu_block"

projects[metatags_quick][subdir] = "sites/all/modules/contrib/metatags_quick"

projects[references][subdir] = "sites/all/modules/contrib/references"

projects[nodereference_url][subdir] = "sites/all/modules/contrib/nodereference_url"

projects[override_node_options][subdir] = "sites/all/modules/contrib/override_node_options"

projects[page_title][subdir] = "sites/all/modules/contrib/page_title"

projects[pathauto][subdir] = "sites/all/modules/contrib/pathauto"

projects[quicktabs][subdir] = "sites/all/modules/contrib/quicktabs"

projects[redirect][subdir] = "sites/all/modules/contrib/redirect"

projects[rules][subdir] = "sites/all/modules/contrib/rules"

projects[search_api][subdir] = "sites/all/modules/contrib/search_api"

projects[search_api_solr][subdir] = "sites/all/modules/contrib/search_api_solr"

projects[site_verify][subdir] = "sites/all/modules/contrib/site_verify"

projects[smtp][subdir] = "sites/all/modules/contrib/smtp"

projects[strongarm][subdir] = "sites/all/modules/contrib/strongarm"

projects[taxonomy_csv][subdir] = "sites/all/modules/contrib/taxonomy_csv"

projects[token][subdir] = "sites/all/modules/contrib/token"

projects[uuid][subdir] = "sites/all/modules/contrib/uuid"

projects[variable][subdir] = "sites/all/modules/contrib/variable"

projects[varnish][subdir] = "sites/all/modules/contrib/varnish"

projects[views][subdir] = "sites/all/modules/contrib/views"

projects[views_autocomplete_filters][subdir] = "sites/all/modules/contrib/views_autocomplete_filters"

projects[views_php][subdir] = "sites/all/modules/contrib/views_php"


; THEME ENGINES & THEMES

projects[fusion][subdir] = "sites/all/themes"

projects[fusion][omega] = "sites/all/themes"


; LIBRARIES

libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][destination] = "libraries"

libraries[geophp][download][type] = "get"
libraries[geophp][download][url] = "https://github.com/downloads/phayes/geoPHP/geophp.tar.gz"
libraries[geophp][directory_name] = "geoPHP"
libraries[geophp][destination] = "libraries"

libraries[openlayers_lib][download][type] = "get"
libraries[openlayers_lib][download][url] = "http://openlayers.org/download/OpenLayers-2.11.tar.gz"
libraries[openlayers_lib][directory_name] = "openlayers"
libraries[openlayers_lib][destination] = "libraries"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%203.6.2%20for%20Drupal/ckeditor_3.6.2_for_drupal_7.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "libraries"

libraries[SolrPhpClient][download][type] = "get"
libraries[SolrPhpClient][download][url] = "http://solr-php-client.googlecode.com/files/SolrPhpClient.r22.2009-11-09.tgz"
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][destination] = "libraries"